# SPDX-License-Identifier: 0BSD
# last update: 2026-02-11
# https://github.com/hannob/codingstyle
---
name: runshci
"on":
  - pull_request
  - push

jobs:
  shellci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get -y install shfmt
      - name: Run tests
        run: |
          ./runshci.sh
